package migrations

import (
	"github.com/muharihar/d3ta-go/database/base"
	geoModel "github.com/muharihar/d3ta-go/modules/geolocation/crud/domain/model"
	"github.com/muharihar/d3ta-go/system/handler"

	_ "gorm.io/driver/mysql"
	_ "gorm.io/driver/postgres"
	_ "gorm.io/driver/sqlite"
	_ "gorm.io/driver/sqlserver"
	"gorm.io/gorm"
)

// NewMS0201SeedDataGeo new MS0201SeedDataGeo
func NewMS0201SeedDataGeo(h *handler.Handler) base.IMigration {
	m := new(MS0201SeedDataGeo)
	m.handler = h

	return m
}

// MS0201SeedDataGeo type
type MS0201SeedDataGeo struct {
	BaseMigration
}

// Run migration
func (ms01 *MS0201SeedDataGeo) Run(db *gorm.DB) error {
	// DB GeoLocation
	// we can move it lo json file later
	gCountries := []geoModel.Country{
		{Code: "AW", Name: "ARUBA", ISO2Code: "AW", ISO3Code: "ABW", WHORegion: "AMRO"},
		{Code: "AF", Name: "AFGHANISTAN", ISO2Code: "AF", ISO3Code: "AFG", WHORegion: "EMRO"},
		{Code: "AO", Name: "ANGOLA", ISO2Code: "AO", ISO3Code: "AGO", WHORegion: "AFRO"},
		{Code: "AI", Name: "ANGUILLA", ISO2Code: "AI", ISO3Code: "AIA", WHORegion: "AMRO"},
		{Code: "AL", Name: "ALBANIA", ISO2Code: "AL", ISO3Code: "ALB", WHORegion: "EURO"},
		{Code: "AD", Name: "ANDORRA", ISO2Code: "AD", ISO3Code: "AND", WHORegion: "EURO"},
		{Code: "AE", Name: "UNITED ARAB EMIRATES", ISO2Code: "AE", ISO3Code: "ARE", WHORegion: "EMRO"},
		{Code: "AR", Name: "ARGENTINA", ISO2Code: "AR", ISO3Code: "ARG", WHORegion: "AMRO"},
		{Code: "AM", Name: "ARMENIA", ISO2Code: "AM", ISO3Code: "ARM", WHORegion: "EURO"},
		{Code: "AS", Name: "AMERICAN SAMOA", ISO2Code: "AS", ISO3Code: "ASM", WHORegion: "WPRO"},
		{Code: "AG", Name: "ANTIGUA AND BARBUDA", ISO2Code: "AG", ISO3Code: "ATG", WHORegion: "AMRO"},
		{Code: "AU", Name: "AUSTRALIA", ISO2Code: "AU", ISO3Code: "AUS", WHORegion: "WPRO"},
		{Code: "AT", Name: "AUSTRIA", ISO2Code: "AT", ISO3Code: "AUT", WHORegion: "EURO"},
		{Code: "AZ", Name: "AZERBAIJAN", ISO2Code: "AZ", ISO3Code: "AZE", WHORegion: "EURO"},
		{Code: "BI", Name: "BURUNDI", ISO2Code: "BI", ISO3Code: "BDI", WHORegion: "AFRO"},
		{Code: "BE", Name: "BELGIUM", ISO2Code: "BE", ISO3Code: "BEL", WHORegion: "EURO"},
		{Code: "BJ", Name: "BENIN", ISO2Code: "BJ", ISO3Code: "BEN", WHORegion: "AFRO"},
		{Code: "BQ", Name: "BONAIRE, SINT EUSTATIUS AND SABA", ISO2Code: "BQ", ISO3Code: "BES", WHORegion: "AMRO"},
		{Code: "BF", Name: "BURKINA FASO", ISO2Code: "BF", ISO3Code: "BFA", WHORegion: "AFRO"},
		{Code: "BD", Name: "BANGLADESH", ISO2Code: "BD", ISO3Code: "BGD", WHORegion: "SEARO"},
		{Code: "BG", Name: "BULGARIA", ISO2Code: "BG", ISO3Code: "BGR", WHORegion: "EURO"},
		{Code: "BH", Name: "BAHRAIN", ISO2Code: "BH", ISO3Code: "BHR", WHORegion: "EMRO"},
		{Code: "BS", Name: "BAHAMAS", ISO2Code: "BS", ISO3Code: "BHS", WHORegion: "AMRO"},
		{Code: "BA", Name: "BOSNIA AND HERZEGOVINA", ISO2Code: "BA", ISO3Code: "BIH", WHORegion: "EURO"},
		{Code: "BL", Name: "SAINT BARTHELEMY", ISO2Code: "BL", ISO3Code: "BLM", WHORegion: "AMRO"},
		{Code: "BY", Name: "BELARUS", ISO2Code: "BY", ISO3Code: "BLR", WHORegion: "EURO"},
		{Code: "BZ", Name: "BELIZE", ISO2Code: "BZ", ISO3Code: "BLZ", WHORegion: "AMRO"},
		{Code: "BM", Name: "BERMUDA", ISO2Code: "BM", ISO3Code: "BMU", WHORegion: "AMRO"},
		{Code: "BO", Name: "PLURINATIONAL STATE OF BOLIVIA", ISO2Code: "BO", ISO3Code: "BOL", WHORegion: "AMRO"},
		{Code: "BR", Name: "BRAZIL", ISO2Code: "BR", ISO3Code: "BRA", WHORegion: "AMRO"},
		{Code: "BB", Name: "BARBADOS", ISO2Code: "BB", ISO3Code: "BRB", WHORegion: "AMRO"},
		{Code: "BN", Name: "BRUNEI DARUSSALAM", ISO2Code: "BN", ISO3Code: "BRN", WHORegion: "WPRO"},
		{Code: "BT", Name: "BHUTAN", ISO2Code: "BT", ISO3Code: "BTN", WHORegion: "SEARO"},
		{Code: "BW", Name: "BOTSWANA", ISO2Code: "BW", ISO3Code: "BWA", WHORegion: "AFRO"},
		{Code: "CF", Name: "CENTRAL AFRICAN REPUBLIC", ISO2Code: "CF", ISO3Code: "CAF", WHORegion: "AFRO"},
		{Code: "CA", Name: "CANADA", ISO2Code: "CA", ISO3Code: "CAN", WHORegion: "AMRO"},
		{Code: "CC", Name: "COCOS (KEELING) ISLANDS", ISO2Code: "CC", ISO3Code: "CCK", WHORegion: "WPRO"},
		{Code: "CH", Name: "SWITZERLAND", ISO2Code: "CH", ISO3Code: "CHE", WHORegion: "EURO"},
		{Code: "CL", Name: "CHILE", ISO2Code: "CL", ISO3Code: "CHL", WHORegion: "AMRO"},
		{Code: "CN", Name: "CHINA", ISO2Code: "CN", ISO3Code: "CHN", WHORegion: "WPRO"},
		{Code: "CM", Name: "CAMEROON", ISO2Code: "CM", ISO3Code: "CMR", WHORegion: "AFRO"},
		{Code: "CK", Name: "COOK ISLANDS", ISO2Code: "CK", ISO3Code: "COK", WHORegion: "WPRO"},
		{Code: "CO", Name: "COLOMBIA", ISO2Code: "CO", ISO3Code: "COL", WHORegion: "AMRO"},
		{Code: "KM", Name: "COMOROS", ISO2Code: "KM", ISO3Code: "COM", WHORegion: "AFRO"},
		{Code: "CV", Name: "CABO VERDE", ISO2Code: "CV", ISO3Code: "CPV", WHORegion: "AFRO"},
		{Code: "CR", Name: "COSTA RICA", ISO2Code: "CR", ISO3Code: "CRI", WHORegion: "AMRO"},
		{Code: "CU", Name: "CUBA", ISO2Code: "CU", ISO3Code: "CUB", WHORegion: "AMRO"},
		{Code: "CW", Name: "CURACAO", ISO2Code: "CW", ISO3Code: "CUW", WHORegion: "AMRO"},
		{Code: "CX", Name: "CHRISTMAS ISLAND", ISO2Code: "CX", ISO3Code: "CXR", WHORegion: "WPRO"},
		{Code: "KY", Name: "CAYMAN ISLANDS", ISO2Code: "KY", ISO3Code: "CYM", WHORegion: "AMRO"},
		{Code: "CY", Name: "CYPRUS", ISO2Code: "CY", ISO3Code: "CYP", WHORegion: "EURO"},
		{Code: "CZ", Name: "CZECH REPUBLIC", ISO2Code: "CZ", ISO3Code: "CZE", WHORegion: "EURO"},
		{Code: "DE", Name: "GERMANY", ISO2Code: "DE", ISO3Code: "DEU", WHORegion: "EURO"},
		{Code: "DJ", Name: "DJIBOUTI", ISO2Code: "DJ", ISO3Code: "DJI", WHORegion: "EMRO"},
		{Code: "DM", Name: "DOMINICA", ISO2Code: "DM", ISO3Code: "DMA", WHORegion: "AMRO"},
		{Code: "DK", Name: "DENMARK", ISO2Code: "DK", ISO3Code: "DNK", WHORegion: "EURO"},
		{Code: "DO", Name: "DOMINICAN REPUBLIC", ISO2Code: "DO", ISO3Code: "DOM", WHORegion: "AMRO"},
		{Code: "DZ", Name: "ALGERIA", ISO2Code: "DZ", ISO3Code: "DZA", WHORegion: "AFRO"},
		{Code: "EC", Name: "ECUADOR", ISO2Code: "EC", ISO3Code: "ECU", WHORegion: "AMRO"},
		{Code: "EG", Name: "EGYPT", ISO2Code: "EG", ISO3Code: "EGY", WHORegion: "EMRO"},
		{Code: "ER", Name: "ERITREA", ISO2Code: "ER", ISO3Code: "ERI", WHORegion: "AFRO"},
		{Code: "EH", Name: "WESTERN SAHARA", ISO2Code: "EH", ISO3Code: "ESH", WHORegion: "AFRO"},
		{Code: "ES", Name: "SPAIN", ISO2Code: "ES", ISO3Code: "ESP", WHORegion: "EURO"},
		{Code: "EE", Name: "ESTONIA", ISO2Code: "EE", ISO3Code: "EST", WHORegion: "EURO"},
		{Code: "ET", Name: "ETHIOPIA", ISO2Code: "ET", ISO3Code: "ETH", WHORegion: "AFRO"},
		{Code: "FI", Name: "FINLAND", ISO2Code: "FI", ISO3Code: "FIN", WHORegion: "EURO"},
		{Code: "FJ", Name: "FIJI", ISO2Code: "FJ", ISO3Code: "FJI", WHORegion: "WPRO"},
		{Code: "FK", Name: "FALKLAND ISLANDS (MALVINAS)", ISO2Code: "FK", ISO3Code: "FLK", WHORegion: "AMRO"},
		{Code: "FR", Name: "FRANCE", ISO2Code: "FR", ISO3Code: "FRA", WHORegion: "EURO"},
		{Code: "FO", Name: "FAROE ISLANDS", ISO2Code: "FO", ISO3Code: "FRO", WHORegion: "EURO"},
		{Code: "FM", Name: "FEDERATED STATES OF MICRONESIA", ISO2Code: "FM", ISO3Code: "FSM", WHORegion: "WPRO"},
		{Code: "GA", Name: "GABON", ISO2Code: "GA", ISO3Code: "GAB", WHORegion: "AFRO"},
		{Code: "GE", Name: "GEORGIA", ISO2Code: "GE", ISO3Code: "GEO", WHORegion: "EURO"},
		{Code: "GG", Name: "GUERNSEY", ISO2Code: "GG", ISO3Code: "GGY", WHORegion: "EURO"},
		{Code: "GH", Name: "GHANA", ISO2Code: "GH", ISO3Code: "GHA", WHORegion: "AFRO"},
		{Code: "GI", Name: "GIBRALTAR", ISO2Code: "GI", ISO3Code: "GIB", WHORegion: "EURO"},
		{Code: "GN", Name: "GUINEA", ISO2Code: "GN", ISO3Code: "GIN", WHORegion: "AFRO"},
		{Code: "GP", Name: "GUADELOUPE", ISO2Code: "GP", ISO3Code: "GLP", WHORegion: "AMRO"},
		{Code: "GM", Name: "GAMBIA", ISO2Code: "GM", ISO3Code: "GMB", WHORegion: "AFRO"},
		{Code: "GW", Name: "GUINEA-BISSAU", ISO2Code: "GW", ISO3Code: "GNB", WHORegion: "AFRO"},
		{Code: "GQ", Name: "EQUATORIAL GUINEA", ISO2Code: "GQ", ISO3Code: "GNQ", WHORegion: "AFRO"},
		{Code: "GR", Name: "GREECE", ISO2Code: "GR", ISO3Code: "GRC", WHORegion: "EURO"},
		{Code: "GD", Name: "GRENADA", ISO2Code: "GD", ISO3Code: "GRD", WHORegion: "AMRO"},
		{Code: "GL", Name: "GREENLAND", ISO2Code: "GL", ISO3Code: "GRL", WHORegion: "EURO"},
		{Code: "GT", Name: "GUATEMALA", ISO2Code: "GT", ISO3Code: "GTM", WHORegion: "AMRO"},
		{Code: "GF", Name: "FRENCH GUIANA", ISO2Code: "GF", ISO3Code: "GUF", WHORegion: "AMRO"},
		{Code: "GU", Name: "GUAM", ISO2Code: "GU", ISO3Code: "GUM", WHORegion: "WPRO"},
		{Code: "GY", Name: "GUYANA", ISO2Code: "GY", ISO3Code: "GUY", WHORegion: "AMRO"},
		{Code: "HN", Name: "HONDURAS", ISO2Code: "HN", ISO3Code: "HND", WHORegion: "AMRO"},
		{Code: "HR", Name: "CROATIA", ISO2Code: "HR", ISO3Code: "HRV", WHORegion: "EURO"},
		{Code: "HT", Name: "HAITI", ISO2Code: "HT", ISO3Code: "HTI", WHORegion: "AMRO"},
		{Code: "HU", Name: "HUNGARY", ISO2Code: "HU", ISO3Code: "HUN", WHORegion: "EURO"},
		{Code: "ID", Name: "INDONESIA", ISO2Code: "ID", ISO3Code: "IDN", WHORegion: "SEARO"},
		{Code: "IM", Name: "ISLE OF MAN", ISO2Code: "IM", ISO3Code: "IMN", WHORegion: "EURO"},
		{Code: "IN", Name: "INDIA", ISO2Code: "IN", ISO3Code: "IND", WHORegion: "SEARO"},
		{Code: "IE", Name: "IRELAND", ISO2Code: "IE", ISO3Code: "IRL", WHORegion: "EURO"},
		{Code: "IR", Name: "ISLAMIC REPUBLIC OF IRAN", ISO2Code: "IR", ISO3Code: "IRN", WHORegion: "EMRO"},
		{Code: "IQ", Name: "IRAQ", ISO2Code: "IQ", ISO3Code: "IRQ", WHORegion: "EMRO"},
		{Code: "IS", Name: "ICELAND", ISO2Code: "IS", ISO3Code: "ISL", WHORegion: "EURO"},
		{Code: "IL", Name: "ISRAEL", ISO2Code: "IL", ISO3Code: "ISR", WHORegion: "EURO"},
		{Code: "IT", Name: "ITALY", ISO2Code: "IT", ISO3Code: "ITA", WHORegion: "EURO"},
		{Code: "JM", Name: "JAMAICA", ISO2Code: "JM", ISO3Code: "JAM", WHORegion: "AMRO"},
		{Code: "JE", Name: "JERSEY", ISO2Code: "JE", ISO3Code: "JEY", WHORegion: "EURO"},
		{Code: "JO", Name: "JORDAN", ISO2Code: "JO", ISO3Code: "JOR", WHORegion: "EMRO"},
		{Code: "JP", Name: "JAPAN", ISO2Code: "JP", ISO3Code: "JPN", WHORegion: "WPRO"},
		{Code: "KZ", Name: "KAZAKHSTAN", ISO2Code: "KZ", ISO3Code: "KAZ", WHORegion: "EURO"},
		{Code: "KE", Name: "KENYA", ISO2Code: "KE", ISO3Code: "KEN", WHORegion: "AFRO"},
		{Code: "KG", Name: "KYRGYZSTAN", ISO2Code: "KG", ISO3Code: "KGZ", WHORegion: "EURO"},
		{Code: "KH", Name: "CAMBODIA", ISO2Code: "KH", ISO3Code: "KHM", WHORegion: "WPRO"},
		{Code: "KI", Name: "KIRIBATI", ISO2Code: "KI", ISO3Code: "KIR", WHORegion: "WPRO"},
		{Code: "KN", Name: "SAINT KITTS AND NEVIS", ISO2Code: "KN", ISO3Code: "KNA", WHORegion: "AMRO"},
		{Code: "KR", Name: "REPUBLIC OF KOREA", ISO2Code: "KR", ISO3Code: "KOR", WHORegion: "WPRO"},
		{Code: "KW", Name: "KUWAIT", ISO2Code: "KW", ISO3Code: "KWT", WHORegion: "EMRO"},
		{Code: "LA", Name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC", ISO2Code: "LA", ISO3Code: "LAO", WHORegion: "WPRO"},
		{Code: "LB", Name: "LEBANON", ISO2Code: "LB", ISO3Code: "LBN", WHORegion: "EMRO"},
		{Code: "LR", Name: "LIBERIA", ISO2Code: "LR", ISO3Code: "LBR", WHORegion: "AFRO"},
		{Code: "LY", Name: "LIBYA", ISO2Code: "LY", ISO3Code: "LBY", WHORegion: "EMRO"},
		{Code: "LC", Name: "SAINT LUCIA", ISO2Code: "LC", ISO3Code: "LCA", WHORegion: "AMRO"},
		{Code: "LI", Name: "LIECHTENSTEIN", ISO2Code: "LI", ISO3Code: "LIE", WHORegion: "EURO"},
		{Code: "LK", Name: "SRI LANKA", ISO2Code: "LK", ISO3Code: "LKA", WHORegion: "SEARO"},
		{Code: "LS", Name: "LESOTHO", ISO2Code: "LS", ISO3Code: "LSO", WHORegion: "AFRO"},
		{Code: "LT", Name: "LITHUANIA", ISO2Code: "LT", ISO3Code: "LTU", WHORegion: "EURO"},
		{Code: "LU", Name: "LUXEMBOURG", ISO2Code: "LU", ISO3Code: "LUX", WHORegion: "EURO"},
		{Code: "LV", Name: "LATVIA", ISO2Code: "LV", ISO3Code: "LVA", WHORegion: "EURO"},
		{Code: "MF", Name: "SAINT MARTIN", ISO2Code: "MF", ISO3Code: "MAF", WHORegion: "AMRO"},
		{Code: "MA", Name: "MOROCCO", ISO2Code: "MA", ISO3Code: "MAR", WHORegion: "EMRO"},
		{Code: "MC", Name: "MONACO", ISO2Code: "MC", ISO3Code: "MCO", WHORegion: "EURO"},
		{Code: "MD", Name: "REPUBLIC OF MOLDOVA", ISO2Code: "MD", ISO3Code: "MDA", WHORegion: "EURO"},
		{Code: "MG", Name: "MADAGASCAR", ISO2Code: "MG", ISO3Code: "MDG", WHORegion: "AFRO"},
		{Code: "MV", Name: "MALDIVES", ISO2Code: "MV", ISO3Code: "MDV", WHORegion: "SEARO"},
		{Code: "MX", Name: "MEXICO", ISO2Code: "MX", ISO3Code: "MEX", WHORegion: "AMRO"},
		{Code: "MH", Name: "MARSHALL ISLANDS", ISO2Code: "MH", ISO3Code: "MHL", WHORegion: "WPRO"},
		{Code: "MK", Name: "NORTH MACEDONIA", ISO2Code: "MK", ISO3Code: "MKD", WHORegion: "EURO"},
		{Code: "ML", Name: "MALI", ISO2Code: "ML", ISO3Code: "MLI", WHORegion: "AFRO"},
		{Code: "MT", Name: "MALTA", ISO2Code: "MT", ISO3Code: "MLT", WHORegion: "EURO"},
		{Code: "MM", Name: "MYANMAR", ISO2Code: "MM", ISO3Code: "MMR", WHORegion: "SEARO"},
		{Code: "ME", Name: "MONTENEGRO", ISO2Code: "ME", ISO3Code: "MNE", WHORegion: "EURO"},
		{Code: "MN", Name: "MONGOLIA", ISO2Code: "MN", ISO3Code: "MNG", WHORegion: "WPRO"},
		{Code: "MP", Name: "NORTHERN MARIANA ISLANDS, COMMONWEALTH OF THE", ISO2Code: "MP", ISO3Code: "MNP", WHORegion: "WPRO"},
		{Code: "MZ", Name: "MOZAMBIQUE", ISO2Code: "MZ", ISO3Code: "MOZ", WHORegion: "AFRO"},
		{Code: "MR", Name: "MAURITANIA", ISO2Code: "MR", ISO3Code: "MRT", WHORegion: "AFRO"},
		{Code: "MS", Name: "MONTSERRAT", ISO2Code: "MS", ISO3Code: "MSR", WHORegion: "AMRO"},
		{Code: "MQ", Name: "MARTINIQUE", ISO2Code: "MQ", ISO3Code: "MTQ", WHORegion: "AMRO"},
		{Code: "MU", Name: "MAURITIUS", ISO2Code: "MU", ISO3Code: "MUS", WHORegion: "AFRO"},
		{Code: "MW", Name: "MALAWI", ISO2Code: "MW", ISO3Code: "MWI", WHORegion: "AFRO"},
		{Code: "MY", Name: "MALAYSIA", ISO2Code: "MY", ISO3Code: "MYS", WHORegion: "WPRO"},
		{Code: "YT", Name: "MAYOTTE", ISO2Code: "YT", ISO3Code: "MYT", WHORegion: "AFRO"},
		{Code: "NA", Name: "NAMIBIA", ISO2Code: "NA", ISO3Code: "NAM", WHORegion: "AFRO"},
		{Code: "NC", Name: "NEW CALEDONIA", ISO2Code: "NC", ISO3Code: "NCL", WHORegion: "WPRO"},
		{Code: "NE", Name: "NIGER", ISO2Code: "NE", ISO3Code: "NER", WHORegion: "AFRO"},
		{Code: "NF", Name: "NORFOLK ISLAND", ISO2Code: "NF", ISO3Code: "NFK", WHORegion: "WPRO"},
		{Code: "NG", Name: "NIGERIA", ISO2Code: "NG", ISO3Code: "NGA", WHORegion: "AFRO"},
		{Code: "NI", Name: "NICARAGUA", ISO2Code: "NI", ISO3Code: "NIC", WHORegion: "AMRO"},
		{Code: "NU", Name: "NIUE", ISO2Code: "NU", ISO3Code: "NIU", WHORegion: "WPRO"},
		{Code: "NL", Name: "NETHERLANDS", ISO2Code: "NL", ISO3Code: "NLD", WHORegion: "EURO"},
		{Code: "NO", Name: "NORWAY", ISO2Code: "NO", ISO3Code: "NOR", WHORegion: "EURO"},
		{Code: "NP", Name: "NEPAL", ISO2Code: "NP", ISO3Code: "NPL", WHORegion: "SEARO"},
		{Code: "NR", Name: "NAURU", ISO2Code: "NR", ISO3Code: "NRU", WHORegion: "WPRO"},
		{Code: "NZ", Name: "NEW ZEALAND", ISO2Code: "NZ", ISO3Code: "NZL", WHORegion: "WPRO"},
		{Code: "OM", Name: "OMAN", ISO2Code: "OM", ISO3Code: "OMN", WHORegion: "EMRO"},
		{Code: "PK", Name: "PAKISTAN", ISO2Code: "PK", ISO3Code: "PAK", WHORegion: "EMRO"},
		{Code: "PA", Name: "PANAMA", ISO2Code: "PA", ISO3Code: "PAN", WHORegion: "AMRO"},
		{Code: "PN", Name: "PITCAIRN ISLANDS", ISO2Code: "PN", ISO3Code: "PCN", WHORegion: "WPRO"},
		{Code: "PE", Name: "PERU", ISO2Code: "PE", ISO3Code: "PER", WHORegion: "AMRO"},
		{Code: "PH", Name: "PHILIPPINES", ISO2Code: "PH", ISO3Code: "PHL", WHORegion: "WPRO"},
		{Code: "PW", Name: "PALAU", ISO2Code: "PW", ISO3Code: "PLW", WHORegion: "WPRO"},
		{Code: "PL", Name: "POLAND", ISO2Code: "PL", ISO3Code: "POL", WHORegion: "EURO"},
		{Code: "PR", Name: "PUERTO RICO", ISO2Code: "PR", ISO3Code: "PRI", WHORegion: "AMRO"},
		{Code: "KP", Name: "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA", ISO2Code: "KP", ISO3Code: "PRK", WHORegion: "SEARO"},
		{Code: "PT", Name: "PORTUGAL", ISO2Code: "PT", ISO3Code: "PRT", WHORegion: "EURO"},
		{Code: "PY", Name: "PARAGUAY", ISO2Code: "PY", ISO3Code: "PRY", WHORegion: "AMRO"},
		{Code: "PS", Name: "OCCUPIED PALESTINIAN TERRITORY", ISO2Code: "PS", ISO3Code: "PSE", WHORegion: "EMRO"},
		{Code: "PF", Name: "FRENCH POLYNESIA", ISO2Code: "PF", ISO3Code: "PYF", WHORegion: "WPRO"},
		{Code: "QA", Name: "QATAR", ISO2Code: "QA", ISO3Code: "QAT", WHORegion: "EMRO"},
		{Code: "RE", Name: "RÉUNION", ISO2Code: "RE", ISO3Code: "REU", WHORegion: "AFRO"},
		{Code: "RO", Name: "ROMANIA", ISO2Code: "RO", ISO3Code: "ROU", WHORegion: "EURO"},
		{Code: "RU", Name: "RUSSIAN FEDERATION", ISO2Code: "RU", ISO3Code: "RUS", WHORegion: "EURO"},
		{Code: "RW", Name: "RWANDA", ISO2Code: "RW", ISO3Code: "RWA", WHORegion: "AFRO"},
		{Code: "SA", Name: "SAUDI ARABIA", ISO2Code: "SA", ISO3Code: "SAU", WHORegion: "EMRO"},
		{Code: "SD", Name: "SUDAN", ISO2Code: "SD", ISO3Code: "SDN", WHORegion: "EMRO"},
		{Code: "SN", Name: "SENEGAL", ISO2Code: "SN", ISO3Code: "SEN", WHORegion: "AFRO"},
		{Code: "SG", Name: "SINGAPORE", ISO2Code: "SG", ISO3Code: "SGP", WHORegion: "WPRO"},
		{Code: "SH", Name: "SAINT HELENA", ISO2Code: "SH", ISO3Code: "SHN", WHORegion: "AFRO"},
		{Code: "SJ", Name: "SVALBARD AND JAN MAYEN ISLANDS", ISO2Code: "SJ", ISO3Code: "SJM", WHORegion: "EURO"},
		{Code: "SB", Name: "SOLOMON ISLANDS", ISO2Code: "SB", ISO3Code: "SLB", WHORegion: "WPRO"},
		{Code: "SL", Name: "SIERRA LEONE", ISO2Code: "SL", ISO3Code: "SLE", WHORegion: "AFRO"},
		{Code: "SV", Name: "EL SALVADOR", ISO2Code: "SV", ISO3Code: "SLV", WHORegion: "AMRO"},
		{Code: "SM", Name: "SAN MARINO", ISO2Code: "SM", ISO3Code: "SMR", WHORegion: "EURO"},
		{Code: "SO", Name: "SOMALIA", ISO2Code: "SO", ISO3Code: "SOM", WHORegion: "EMRO"},
		{Code: "PM", Name: "SAINT PIERRE AND MIQUELON", ISO2Code: "PM", ISO3Code: "SPM", WHORegion: "AMRO"},
		{Code: "RS", Name: "SERBIA", ISO2Code: "RS", ISO3Code: "SRB", WHORegion: "EURO"},
		{Code: "SS", Name: "SOUTH SUDAN", ISO2Code: "SS", ISO3Code: "SSD", WHORegion: "AFRO"},
		{Code: "ST", Name: "SAO TOME AND PRINCIPE", ISO2Code: "ST", ISO3Code: "STP", WHORegion: "AFRO"},
		{Code: "SR", Name: "SURINAME", ISO2Code: "SR", ISO3Code: "SUR", WHORegion: "AMRO"},
		{Code: "SK", Name: "SLOVAKIA", ISO2Code: "SK", ISO3Code: "SVK", WHORegion: "EURO"},
		{Code: "SI", Name: "SLOVENIA", ISO2Code: "SI", ISO3Code: "SVN", WHORegion: "EURO"},
		{Code: "SE", Name: "SWEDEN", ISO2Code: "SE", ISO3Code: "SWE", WHORegion: "EURO"},
		{Code: "SZ", Name: "ESWATINI", ISO2Code: "SZ", ISO3Code: "SWZ", WHORegion: "AFRO"},
		{Code: "SX", Name: "SINT MAARTEN", ISO2Code: "SX", ISO3Code: "SXM", WHORegion: "AMRO"},
		{Code: "SC", Name: "SEYCHELLES", ISO2Code: "SC", ISO3Code: "SYC", WHORegion: "AFRO"},
		{Code: "SY", Name: "SYRIAN ARAB REPUBLIC", ISO2Code: "SY", ISO3Code: "SYR", WHORegion: "EMRO"},
		{Code: "TC", Name: "TURKS AND CAICOS ISLANDS", ISO2Code: "TC", ISO3Code: "TCA", WHORegion: "AMRO"},
		{Code: "TD", Name: "CHAD", ISO2Code: "TD", ISO3Code: "TCD", WHORegion: "AFRO"},
		{Code: "TG", Name: "TOGO", ISO2Code: "TG", ISO3Code: "TGO", WHORegion: "AFRO"},
		{Code: "TH", Name: "THAILAND", ISO2Code: "TH", ISO3Code: "THA", WHORegion: "SEARO"},
		{Code: "TJ", Name: "TAJIKISTAN", ISO2Code: "TJ", ISO3Code: "TJK", WHORegion: "EURO"},
		{Code: "TK", Name: "TOKELAU", ISO2Code: "TK", ISO3Code: "TKL", WHORegion: "WPRO"},
		{Code: "TM", Name: "TURKMENISTAN", ISO2Code: "TM", ISO3Code: "TKM", WHORegion: "EURO"},
		{Code: "TL", Name: "TIMOR-LESTE", ISO2Code: "TL", ISO3Code: "TLS", WHORegion: "SEARO"},
		{Code: "TO", Name: "TONGA", ISO2Code: "TO", ISO3Code: "TON", WHORegion: "WPRO"},
		{Code: "TT", Name: "TRINIDAD AND TOBAGO", ISO2Code: "TT", ISO3Code: "TTO", WHORegion: "AMRO"},
		{Code: "TN", Name: "TUNISIA", ISO2Code: "TN", ISO3Code: "TUN", WHORegion: "EMRO"},
		{Code: "TR", Name: "TURKEY", ISO2Code: "TR", ISO3Code: "TUR", WHORegion: "EURO"},
		{Code: "TV", Name: "TUVALU", ISO2Code: "TV", ISO3Code: "TUV", WHORegion: "WPRO"},
		{Code: "TZ", Name: "UNITED REPUBLIC OF TANZANIA", ISO2Code: "TZ", ISO3Code: "TZA", WHORegion: "AFRO"},
		{Code: "UG", Name: "UGANDA", ISO2Code: "UG", ISO3Code: "UGA", WHORegion: "AFRO"},
		{Code: "UA", Name: "UKRAINE", ISO2Code: "UA", ISO3Code: "UKR", WHORegion: "EURO"},
		{Code: "UY", Name: "URUGUAY", ISO2Code: "UY", ISO3Code: "URY", WHORegion: "AMRO"},
		{Code: "US", Name: "UNITED STATES OF AMERICA", ISO2Code: "US", ISO3Code: "USA", WHORegion: "AMRO"},
		{Code: "UZ", Name: "UZBEKISTAN", ISO2Code: "UZ", ISO3Code: "UZB", WHORegion: "EURO"},
		{Code: "VA", Name: "HOLY SEE", ISO2Code: "VA", ISO3Code: "VAT", WHORegion: "EURO"},
		{Code: "VC", Name: "SAINT VINCENT AND THE GRENADINES", ISO2Code: "VC", ISO3Code: "VCT", WHORegion: "AMRO"},
		{Code: "VE", Name: "BOLIVARIAN REPUBLIC OF VENEZUELA", ISO2Code: "VE", ISO3Code: "VEN", WHORegion: "AMRO"},
		{Code: "VG", Name: "BRITISH VIRGIN ISLANDS", ISO2Code: "VG", ISO3Code: "VGB", WHORegion: "AMRO"},
		{Code: "VI", Name: "UNITED STATES VIRGIN ISLANDS", ISO2Code: "VI", ISO3Code: "VIR", WHORegion: "AMRO"},
		{Code: "VN", Name: "VIET NAM", ISO2Code: "VN", ISO3Code: "VNM", WHORegion: "WPRO"},
		{Code: "VU", Name: "VANUATU", ISO2Code: "VU", ISO3Code: "VUT", WHORegion: "WPRO"},
		{Code: "WF", Name: "WALLIS AND FUTUNA", ISO2Code: "WF", ISO3Code: "WLF", WHORegion: "WPRO"},
		{Code: "WS", Name: "SAMOA", ISO2Code: "WS", ISO3Code: "WSM", WHORegion: "WPRO"},
		{Code: "YE", Name: "YEMEN", ISO2Code: "YE", ISO3Code: "YEM", WHORegion: "EMRO"},
		{Code: "ZA", Name: "SOUTH AFRICA", ISO2Code: "ZA", ISO3Code: "ZAF", WHORegion: "AFRO"},
		{Code: "ZM", Name: "ZAMBIA", ISO2Code: "ZM", ISO3Code: "ZMB", WHORegion: "AFRO"},
		{Code: "ZW", Name: "ZIMBABWE", ISO2Code: "ZW", ISO3Code: "ZWE", WHORegion: "AFRO"},
		{Code: "CD", Name: "DEMOCRATIC REPUBLIC OF THE CONGO", ISO2Code: "CD", ISO3Code: "COD", WHORegion: "AFRO"},
		{Code: "CG", Name: "CONGO", ISO2Code: "CG", ISO3Code: "COG", WHORegion: "AFRO"},
		{Code: "PG", Name: "PAPUA NEW GUINEA", ISO2Code: "PG", ISO3Code: "PNG", WHORegion: "WPRO"},
		{Code: "AN", Name: "NETHERLANDS ANTILLES", ISO2Code: "AN", ISO3Code: "ANT", WHORegion: "AMRO"},
		{Code: "JT", Name: "JOHNSTON ATOLL", ISO2Code: "JT", ISO3Code: "JTN", WHORegion: "WPRO"},
		{Code: "UM", Name: "MIDWAY ISLANDS", ISO2Code: "UM", ISO3Code: "MID", WHORegion: "WPRO"},
		{Code: "WK", Name: "WAKE ISLAND", ISO2Code: "WK", ISO3Code: "WAK", WHORegion: "WPRO"},
		{Code: "CI", Name: "COTE D IVOIRE", ISO2Code: "CI", ISO3Code: "CIV", WHORegion: "AFRO"},
	}

	if err := db.Create(&gCountries).Error; err != nil {
		return err
	}

	return nil
}

// Rollback migration
func (ms01 *MS0201SeedDataGeo) Rollback(db *gorm.DB) error {
	return nil
}
